/**
 * The icon registry — the single source of truth for what an icon *means* in
 * Digital Brain.
 *
 * Rules:
 *  1. One concept, one glyph. "maintenance" must look identical in the
 *     sidebar, in a table cell and on a card. Never reach past this map.
 *  2. Semantic names only. Register `incident`, not `triangle-exclamation`.
 *  3. Import individual icons. No wildcard imports — the bundle carries only
 *     what is listed here.
 *  4. Outline-leaning: the regular (outline) style is used wherever Font
 *     Awesome Free ships one, and solid fills in for arrows, chevrons and the
 *     small glyphs that have no regular cut.
 *
 * Colour is never set here. Callers pass a semantic token class to AppIcon.
 */
import {
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowTrendUp,
  faArrowUp,
  faArrowUpRightFromSquare,
  faBars,
  faBolt,
  faBookOpen,
  faChartColumn,
  faChartLine,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleExclamation,
  faCircleHalfStroke,
  faCircleInfo,
  faClipboardCheck,
  faClipboardList,
  faCodeBranch,
  faCubes,
  faDatabase,
  faDiagramProject,
  faDollarSign,
  faEllipsis,
  faFileArrowDown,
  faFilter,
  faGauge,
  faGaugeHigh,
  faGear,
  faGripVertical,
  faHeartPulse,
  faKey,
  faLayerGroup,
  faListCheck,
  faLock,
  faMagnifyingGlass,
  faMagnifyingGlassChart,
  faMapLocationDot,
  faMicrochip,
  faMinus,
  faNetworkWired,
  faPause,
  faPlay,
  faPlug,
  faPlus,
  faRightFromBracket,
  faRotateLeft,
  faScrewdriverWrench,
  faServer,
  faShieldHalved,
  faSliders,
  faSort,
  faSpinner,
  faStopwatch,
  faSun,
  faTable,
  faTableColumns,
  faTag,
  faTowerBroadcast,
  faTowerCell,
  faTriangleExclamation,
  faTruckFast,
  faUserShield,
  faUsers,
  faWandMagicSparkles,
  faWaveSquare,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import {
  faBell,
  faBuilding,
  faCalendarCheck,
  faCalendarDays,
  faCircle,
  faCircleCheck,
  faCircleDot,
  faClock,
  faCloud,
  faComments,
  faCopy,
  faEnvelope,
  faEye,
  faEyeSlash,
  faFileLines,
  faFlag,
  faHand,
  faHouse,
  faLifeRing,
  faMoon,
  faPaperPlane,
  faSquareCheck,
  faStar,
} from "@fortawesome/free-regular-svg-icons";

export const icons = {
  /* -- navigation: one entry per destination in lib/nav.ts ---------------- */
  dashboard: faTableColumns,
  incident: faTriangleExclamation,
  approval: faSquareCheck,
  alertNoise: faTowerBroadcast,
  problem: faListCheck,
  copilot: faComments,
  rootCause: faMagnifyingGlassChart,
  dependency: faCodeBranch,
  knowledge: faLifeRing,
  serviceHealth: faHeartPulse,
  predictive: faArrowTrendUp,
  changeRisk: faClipboardList,
  capacity: faGauge,
  cost: faDollarSign,
  vendor: faBuilding,
  compliance: faShieldHalved,
  briefing: faFileLines,
  agents: faCubes,
  autonomy: faSliders,
  integrations: faPlug,
  users: faUsers,
  home: faHouse,
  menu: faBars,
  panel: faTableColumns,

  /* -- actions ------------------------------------------------------------ */
  search: faMagnifyingGlass,
  filter: faFilter,
  close: faXmark,
  check: faCheck,
  add: faPlus,
  minus: faMinus,
  more: faEllipsis,
  export: faFileArrowDown,
  send: faPaperPlane,
  copy: faCopy,
  retry: faRotateLeft,
  logout: faRightFromBracket,
  externalLink: faArrowUpRightFromSquare,
  dispatch: faBolt,
  view: faEye,
  hide: faEyeSlash,
  drag: faGripVertical,
  play: faPlay,
  pause: faPause,
  settings: faGear,

  /* -- direction ---------------------------------------------------------- */
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  chevronUp: faChevronUp,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  sort: faSort,

  /* -- system & state ----------------------------------------------------- */
  success: faCircleCheck,
  warning: faTriangleExclamation,
  error: faCircleExclamation,
  info: faCircleInfo,
  pending: faClock,
  sla: faStopwatch,
  loading: faSpinner,
  live: faCircleDot,
  circle: faCircle,
  notification: faBell,
  lock: faLock,
  key: faKey,
  mail: faEnvelope,
  flag: faFlag,
  star: faStar,
  tag: faTag,
  /** A human approval gate — a shield with a person, not a bare plate. */
  shieldAlert: faUserShield,
  human: faHand,
  ai: faWandMagicSparkles,
  /** The appearance toggle. One glyph for both directions — Font Awesome's
   *  sun is a ring of short rays that reads as a gear below ~20px. */
  theme: faCircleHalfStroke,
  themeLight: faSun,
  themeDark: faMoon,
  cloud: faCloud,
  signal: faTowerCell,
  node: faMicrochip,
  activity: faWaveSquare,
  gaugeHigh: faGaugeHigh,

  /* -- fleet / operational estate ----------------------------------------- */
  vehicle: faTruckFast,
  maintenance: faScrewdriverWrench,
  server: faServer,
  database: faDatabase,
  network: faNetworkWired,
  layers: faLayerGroup,
  map: faMapLocationDot,

  /* -- data & documents ---------------------------------------------------- */
  chart: faChartColumn,
  chartLine: faChartLine,
  table: faTable,
  document: faFileLines,
  book: faBookOpen,
  calendar: faCalendarDays,
  schedule: faCalendarCheck,
  checklist: faClipboardCheck,
  money: faDollarSign,
  diagram: faDiagramProject,
} as const;

export type IconName = keyof typeof icons;
