/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertNoiseRouteImport } from './routes/alert-noise'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AutonomyRouteImport } from './routes/autonomy'
import { Route as CapacityRouteImport } from './routes/capacity'
import { Route as ChangeRiskRouteImport } from './routes/change-risk'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CostRouteImport } from './routes/cost'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as ExecutiveBriefingRouteImport } from './routes/executive-briefing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PredictiveRouteImport } from './routes/predictive'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as RootCauseRouteImport } from './routes/root-cause'
import { Route as ServiceHealthRouteImport } from './routes/service-health'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsSlugRouteImport } from './routes/agents.$slug'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsIdRouteImport } from './routes/incidents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertNoiseRoute = AlertNoiseRouteImport.update({
  id: '/alert-noise',
  path: '/alert-noise',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AutonomyRoute = AutonomyRouteImport.update({
  id: '/autonomy',
  path: '/autonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityRoute = CapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeRiskRoute = ChangeRiskRouteImport.update({
  id: '/change-risk',
  path: '/change-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveBriefingRoute = ExecutiveBriefingRouteImport.update({
  id: '/executive-briefing',
  path: '/executive-briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveRoute = PredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const RootCauseRoute = RootCauseRouteImport.update({
  id: '/root-cause',
  path: '/root-cause',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceHealthRoute = ServiceHealthRouteImport.update({
  id: '/service-health',
  path: '/service-health',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsSlugRoute = AgentsSlugRouteImport.update({
  id: '/agents/$slug',
  path: '/agents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIdRoute = IncidentsIdRouteImport.update({
  id: '/incidents/$id',
  path: '/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alert-noise': typeof AlertNoiseRoute
  '/approvals': typeof ApprovalsRoute
  '/autonomy': typeof AutonomyRoute
  '/capacity': typeof CapacityRoute
  '/change-risk': typeof ChangeRiskRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/cost': typeof CostRoute
  '/dependencies': typeof DependenciesRoute
  '/executive-briefing': typeof ExecutiveBriefingRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/predictive': typeof PredictiveRoute
  '/problems': typeof ProblemsRoute
  '/root-cause': typeof RootCauseRoute
  '/service-health': typeof ServiceHealthRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alert-noise': typeof AlertNoiseRoute
  '/approvals': typeof ApprovalsRoute
  '/autonomy': typeof AutonomyRoute
  '/capacity': typeof CapacityRoute
  '/change-risk': typeof ChangeRiskRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/cost': typeof CostRoute
  '/dependencies': typeof DependenciesRoute
  '/executive-briefing': typeof ExecutiveBriefingRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/predictive': typeof PredictiveRoute
  '/problems': typeof ProblemsRoute
  '/root-cause': typeof RootCauseRoute
  '/service-health': typeof ServiceHealthRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/agents': typeof AgentsIndexRoute
  '/incidents': typeof IncidentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alert-noise': typeof AlertNoiseRoute
  '/approvals': typeof ApprovalsRoute
  '/autonomy': typeof AutonomyRoute
  '/capacity': typeof CapacityRoute
  '/change-risk': typeof ChangeRiskRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/cost': typeof CostRoute
  '/dependencies': typeof DependenciesRoute
  '/executive-briefing': typeof ExecutiveBriefingRoute
  '/integrations': typeof IntegrationsRoute
  '/knowledge': typeof KnowledgeRoute
  '/login': typeof LoginRoute
  '/predictive': typeof PredictiveRoute
  '/problems': typeof ProblemsRoute
  '/root-cause': typeof RootCauseRoute
  '/service-health': typeof ServiceHealthRoute
  '/users': typeof UsersRoute
  '/vendors': typeof VendorsRoute
  '/agents/$slug': typeof AgentsSlugRoute
  '/incidents/$id': typeof IncidentsIdRoute
  '/agents/': typeof AgentsIndexRoute
  '/incidents/': typeof IncidentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alert-noise'
    | '/approvals'
    | '/autonomy'
    | '/capacity'
    | '/change-risk'
    | '/compliance'
    | '/copilot'
    | '/cost'
    | '/dependencies'
    | '/executive-briefing'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/predictive'
    | '/problems'
    | '/root-cause'
    | '/service-health'
    | '/users'
    | '/vendors'
    | '/agents/$slug'
    | '/incidents/$id'
    | '/agents/'
    | '/incidents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alert-noise'
    | '/approvals'
    | '/autonomy'
    | '/capacity'
    | '/change-risk'
    | '/compliance'
    | '/copilot'
    | '/cost'
    | '/dependencies'
    | '/executive-briefing'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/predictive'
    | '/problems'
    | '/root-cause'
    | '/service-health'
    | '/users'
    | '/vendors'
    | '/agents/$slug'
    | '/incidents/$id'
    | '/agents'
    | '/incidents'
  id:
    | '__root__'
    | '/'
    | '/alert-noise'
    | '/approvals'
    | '/autonomy'
    | '/capacity'
    | '/change-risk'
    | '/compliance'
    | '/copilot'
    | '/cost'
    | '/dependencies'
    | '/executive-briefing'
    | '/integrations'
    | '/knowledge'
    | '/login'
    | '/predictive'
    | '/problems'
    | '/root-cause'
    | '/service-health'
    | '/users'
    | '/vendors'
    | '/agents/$slug'
    | '/incidents/$id'
    | '/agents/'
    | '/incidents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertNoiseRoute: typeof AlertNoiseRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AutonomyRoute: typeof AutonomyRoute
  CapacityRoute: typeof CapacityRoute
  ChangeRiskRoute: typeof ChangeRiskRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  CostRoute: typeof CostRoute
  DependenciesRoute: typeof DependenciesRoute
  ExecutiveBriefingRoute: typeof ExecutiveBriefingRoute
  IntegrationsRoute: typeof IntegrationsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LoginRoute: typeof LoginRoute
  PredictiveRoute: typeof PredictiveRoute
  ProblemsRoute: typeof ProblemsRoute
  RootCauseRoute: typeof RootCauseRoute
  ServiceHealthRoute: typeof ServiceHealthRoute
  UsersRoute: typeof UsersRoute
  VendorsRoute: typeof VendorsRoute
  AgentsSlugRoute: typeof AgentsSlugRoute
  IncidentsIdRoute: typeof IncidentsIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert-noise': {
      id: '/alert-noise'
      path: '/alert-noise'
      fullPath: '/alert-noise'
      preLoaderRoute: typeof AlertNoiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autonomy': {
      id: '/autonomy'
      path: '/autonomy'
      fullPath: '/autonomy'
      preLoaderRoute: typeof AutonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-risk': {
      id: '/change-risk'
      path: '/change-risk'
      fullPath: '/change-risk'
      preLoaderRoute: typeof ChangeRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-briefing': {
      id: '/executive-briefing'
      path: '/executive-briefing'
      fullPath: '/executive-briefing'
      preLoaderRoute: typeof ExecutiveBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive': {
      id: '/predictive'
      path: '/predictive'
      fullPath: '/predictive'
      preLoaderRoute: typeof PredictiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/root-cause': {
      id: '/root-cause'
      path: '/root-cause'
      fullPath: '/root-cause'
      preLoaderRoute: typeof RootCauseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-health': {
      id: '/service-health'
      path: '/service-health'
      fullPath: '/service-health'
      preLoaderRoute: typeof ServiceHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$slug': {
      id: '/agents/$slug'
      path: '/agents/$slug'
      fullPath: '/agents/$slug'
      preLoaderRoute: typeof AgentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$id': {
      id: '/incidents/$id'
      path: '/incidents/$id'
      fullPath: '/incidents/$id'
      preLoaderRoute: typeof IncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertNoiseRoute: AlertNoiseRoute,
  ApprovalsRoute: ApprovalsRoute,
  AutonomyRoute: AutonomyRoute,
  CapacityRoute: CapacityRoute,
  ChangeRiskRoute: ChangeRiskRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  CostRoute: CostRoute,
  DependenciesRoute: DependenciesRoute,
  ExecutiveBriefingRoute: ExecutiveBriefingRoute,
  IntegrationsRoute: IntegrationsRoute,
  KnowledgeRoute: KnowledgeRoute,
  LoginRoute: LoginRoute,
  PredictiveRoute: PredictiveRoute,
  ProblemsRoute: ProblemsRoute,
  RootCauseRoute: RootCauseRoute,
  ServiceHealthRoute: ServiceHealthRoute,
  UsersRoute: UsersRoute,
  VendorsRoute: VendorsRoute,
  AgentsSlugRoute: AgentsSlugRoute,
  IncidentsIdRoute: IncidentsIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
